import AppKit
import Carbon.HIToolbox

enum TextInserter {
    /// Debug self-test: log instead of pasting.
    nonisolated(unsafe) static var dryRun = false

    /// Pastes `text` into the focused app via ⌘V, then puts the user's clipboard
    /// back — or, with `keeping`, leaves that in the clipboard instead. Marked
    /// transient while pasting so clipboard managers don't record it twice.
    @MainActor
    static func insert(_ text: String, keeping kept: String? = nil) {
        if dryRun { print("[klistra in] \(text)"); return }
        // Our own window (the "Prova" box): type straight into the text view — a
        // posted ⌘V would come back to us and depends on the Edit menu.
        if NSApp.isActive, let textView = NSApp.keyWindow?.firstResponder as? NSTextView, textView.isEditable {
            textView.insertText(text, replacementRange: textView.selectedRange())
            return
        }
        let pb = NSPasteboard.general
        // Two pastes close together (a dictation, then ⌃⌥V): keep the clipboard
        // from before the first one, not our own text.
        let saved: [NSPasteboardItem]?
        if let pending = pendingRestore { saved = pending.items } else { saved = snapshot(pb) }
        pendingRestore?.work.cancel()
        pb.clearContents()
        pb.setString(text, forType: .string)
        // Clipboard managers: not something you copied — don't keep it.
        pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        let ourChange = pb.changeCount

        let source = CGEventSource(stateID: .combinedSessionState)
        let vKey = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)

        // Give the target app time to read the paste, then put your clipboard back —
        // unless something else has written to it meanwhile. A password copied from
        // a password manager (marked concealed) is never put back: it had its moment.
        let work = DispatchWorkItem {
            pendingRestore = nil
            guard pb.changeCount == ourChange else { return }
            if let kept { return copy(kept) }
            pb.clearContents()
            if let saved, !saved.isEmpty { pb.writeObjects(saved) }
        }
        pendingRestore = (saved, work)
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0, execute: work)
    }

    /// Puts `text` in the clipboard, as if you had copied it.
    @MainActor static func copy(_ text: String) {
        if dryRun { print("[urklipp] \(text)"); return }
        pendingRestore?.work.cancel()
        pendingRestore = nil
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
    }

    @MainActor private static var pendingRestore: (items: [NSPasteboardItem]?, work: DispatchWorkItem)?

    /// A copy of the clipboard to restore — nil (restore nothing) when it holds
    /// something secret or short-lived.
    @MainActor private static func snapshot(_ pb: NSPasteboard) -> [NSPasteboardItem]? {
        let secret = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                      "com.agilebits.onepassword"].map { NSPasteboard.PasteboardType(rawValue: $0) }
        let items = pb.pasteboardItems ?? []
        if items.contains(where: { item in item.types.contains(where: secret.contains) }) { return nil }
        return items.map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }
}
